[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript', 'ejs']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'ejs']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['javascript', 'html', 'ejs']
hook_add = '''
    let g:user_emmet_settings = { 'lang':'ja' }
'''
 
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['javascript', 'html', 'ejs']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
